import type { Metadata } from 'next'
import Navbar from '@/widgets/Navbar/UI/Navbar'
import { ReduxProvider } from '@/store/provider'
import { Roboto } from 'next/font/google'
import '../styles/globals.scss'

export const metadata: Metadata = {
  title: 'World Wide News',
  description: 'Generated by create next app',
}

export const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="root" lang="en">
      <body className="root">
        <div className="root-layout">
          <div className={roboto.className}>
            <ReduxProvider>
              <Navbar />
              <main className="content">{children}</main>
            </ReduxProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
