import type { Metadata } from 'next'
import Navbar from '@/widgets/Navbar/UI/Navbar'
import { ReduxProvider } from '@/store/provider'

import '../styles/globals.scss'

export const metadata: Metadata = {
  title: 'World Wide News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="root" lang="en">
      <body className="root">
        <div className="root-layout">
          <ReduxProvider>
            <Navbar />
            <main className="content">{children}</main>
          </ReduxProvider>
        </div>
      </body>
    </html>
  )
}
